name: transport

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/core/**'
      - 'packages/interface/**'
      - 'packages/transport/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/core/**'
      - 'packages/interface/**'
      - 'packages/transport/**'
      - '.github/workflows/transport.yml'
jobs:
  check:
    name: Typecheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - ''
        project:
          - transport
    steps:
      - uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          run_install: true

      - name: Typecheck
        uses: gozala/typescript-error-reporter-action@v1.0.8
        with:
          project: packages/${{matrix.project}}/tsconfig.json
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version:
          - ''
          - latest
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        project:
          - transport

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          run_install: true

      - name: Test (Node)
        run: pnpm run --if-present --dir packages/${{matrix.project}} test:node

      - name: Test (Web)
        run: pnpm run --if-present --dir packages/${{matrix.project}} test:web
